package view;

import controller.ClienteController;
import controller.ProdutoController;
import controller.VendaController;
import model.Cliente;
import model.Produto;
import model.ItemVenda;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    private DecimalFormat df;

    private final VendaController vendaController;
    private final ClienteController clienteController;
    private final ProdutoController produtoController;

    private Cliente clienteAtual;
    private List<Produto> listaProdutosDisponiveis;
    private final List<ItemVenda> carrinho;

    public TelaVenda() {
        initComponents();
        this.vendaController = new VendaController();
        this.clienteController = new ClienteController();
        this.produtoController = new ProdutoController();
        this.carrinho = new ArrayList<>();

        carregarProdutosDisponiveis();
        atualizarTotalCarrinho();
        setLocationRelativeTo(null);
    }

    public void FormattingExample() {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(new Locale("pt", "BR"));
        symbols.setDecimalSeparator(',');
        symbols.setGroupingSeparator('.');

        this.df = new DecimalFormat("R$ #,##0.00", symbols);
    }

    private void carregarProdutosDisponiveis() {
        try {
            listaProdutosDisponiveis = produtoController.buscarTodos();

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("--- Selecione um Produto ---");

            for (Produto p : listaProdutosDisponiveis) {
                // Exibe nome e preço
                model.addElement(p.getNome() + " (R$ " + df.format(p.getPreco()) + ")");
            }
            cmbProduto.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produtos: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private Produto getProdutoSelecionado(String nomeDisplay) {
        if (nomeDisplay == null || nomeDisplay.contains("---")) {
            return null;
        }

        // Remove a parte do preço no final para buscar pelo nome
        String nome = nomeDisplay.substring(0, nomeDisplay.lastIndexOf(" (R$"));

        for (Produto p : listaProdutosDisponiveis) {
            if (p.getNome().equals(nome)) {
                return p;
            }
        }
        return null;
    }

    private void atualizarTabelaCarrinho() {
        DefaultTableModel model = (DefaultTableModel) tblItensVenda.getModel();
        model.setRowCount(0); // Limpa a tabela

        // Define as colunas se necessário
        if (model.getColumnCount() == 0) {
            model.setColumnIdentifiers(new Object[]{"ID Prod.", "Produto", "Qtd", "Preço Unit.", "Subtotal"});
        }

        for (ItemVenda item : carrinho) {
            model.addRow(new Object[]{
                item.getProduto().getId(),
                item.getProduto().getNome(),
                item.getQuantidade(),
                df.format(item.getPrecoUnitario()),
                df.format(item.getSubtotal())
            });
        }
    }

    private void atualizarTotalCarrinho() {
        double total = carrinho.stream()
                .mapToDouble(ItemVenda::getSubtotal)
                .sum();

        lblTotal.setText("VALOR TOTAL: R$ " + df.format(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblClienteNome = new javax.swing.JLabel();
        lblClientePontos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblProdutos = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox<>();
        lblQuantidade = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        btnAdicionarItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnResgatarPontos = new javax.swing.JButton();
        btnFinalizarVenda = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Registro de venda (PDV):");

        lblCpf.setText("CPF do Cliente:");

        btnBuscarCliente.setText("BUSCAR CLIENTE");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblClienteNome.setText("Cliente: Nenhum Cliente Selecionado");

        lblClientePontos.setText("Pontos atuais: 0");

        lblProdutos.setText("Produto:");

        cmbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblQuantidade.setText("Quantidade:");

        spnQuantidade.setModel(new javax.swing.SpinnerNumberModel());

        btnAdicionarItem.setText("Adicionar ao Carrinho");
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        tblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItensVenda);

        lblTotal.setText("VALOR TOTAL: R$ 0,00");

        btnResgatarPontos.setText("RESGATAR ITEM COM PONTOS");

        btnFinalizarVenda.setText("FINALIZAR VENDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProdutos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTitulo)
                            .addComponent(lblClienteNome)
                            .addComponent(lblClientePontos)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnResgatarPontos)
                            .addComponent(btnBuscarCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizarVenda)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCpf)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCliente)))
                .addGap(18, 18, 18)
                .addComponent(lblClienteNome)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientePontos)
                    .addComponent(btnResgatarPontos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutos)
                    .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade)
                    .addComponent(btnAdicionarItem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarVenda)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String cpf = txtCpf.getText().trim().replaceAll("\\D", ""); // Limpa o CPF
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe um CPF para buscar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // ClienteController deve ter um método para buscar por CPF
            Cliente cliente = clienteController.buscarPorCpf(cpf);

            if (cliente != null) {
                this.clienteAtual = cliente;
                lblClienteNome.setText("Cliente: " + cliente.getNome());
                lblClientePontos.setText("Pontos Atuais: " + cliente.getPontosAcumulados());
                JOptionPane.showMessageDialog(this, "Cliente encontrado e selecionado!");
            } else {
                this.clienteAtual = null;
                lblClienteNome.setText("Cliente: Não Encontrado");
                lblClientePontos.setText("Pontos Atuais: 0");
                JOptionPane.showMessageDialog(this, "Cliente não encontrado.", "Erro de Busca", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar cliente: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        Produto produto = getProdutoSelecionado((String) cmbProduto.getSelectedItem());
        int quantidade = (Integer) spnQuantidade.getValue();

        if (produto == null) {
            JOptionPane.showMessageDialog(this, "Selecione um produto válido.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade deve ser maior que zero.", "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (produto.getEstoque() < quantidade) {
            JOptionPane.showMessageDialog(this, "Estoque insuficiente. Disponível: " + produto.getEstoque(), "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Cria o ItemVenda
        double subtotal = produto.getPreco() * quantidade;
        ItemVenda novoItem = new ItemVenda(produto, quantidade, produto.getPreco(), subtotal);

        // Adiciona ao carrinho
        carrinho.add(novoItem);

        // Atualiza UI
        atualizarTabelaCarrinho();
        atualizarTotalCarrinho();

        // Reseta seleção
        cmbProduto.setSelectedIndex(0);
        spnQuantidade.setValue(1);
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnResgatarPontos;
    private javax.swing.JComboBox<String> cmbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClienteNome;
    private javax.swing.JLabel lblClientePontos;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTable tblItensVenda;
    private javax.swing.JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
