package view;

import javax.swing.JOptionPane;
import view.TelaCadastroProduto;
import view.TelaCadastroCliente;
import view.TelaVenda;
import view.TelaRelatorios;

public class TelaPrincipal extends javax.swing.JFrame {
    
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNovaVenda = new javax.swing.JButton();
        btnCadProdutos = new javax.swing.JButton();
        bnCadClientes = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de vendas - CookiesBrilha");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/banner.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 15, 15));

        btnNovaVenda.setBackground(new java.awt.Color(252, 223, 228));
        btnNovaVenda.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Vendas.png"))); // NOI18N
        btnNovaVenda.setText("REGISTRAR NOVA VENDA");
        btnNovaVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovaVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovaVenda);

        btnCadProdutos.setBackground(new java.awt.Color(252, 223, 228));
        btnCadProdutos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnCadProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/cadastrarProduto.png"))); // NOI18N
        btnCadProdutos.setText("CADASTRAR PRODUTO");
        btnCadProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProdutosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadProdutos);

        bnCadClientes.setBackground(new java.awt.Color(252, 223, 228));
        bnCadClientes.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        bnCadClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/addCliente.png"))); // NOI18N
        bnCadClientes.setText("CADASTRAR CLIENTES");
        bnCadClientes.setToolTipText("");
        bnCadClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnCadClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnCadClientesActionPerformed(evt);
            }
        });
        jPanel1.add(bnCadClientes);

        btnRelatorios.setBackground(new java.awt.Color(252, 223, 228));
        btnRelatorios.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/relatorios.png"))); // NOI18N
        btnRelatorios.setText("GERAR RELATÓRIO DE VENDAS");
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        jPanel1.add(btnRelatorios);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        new TelaVenda().setVisible(true);
    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private void btnCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProdutosActionPerformed
        new TelaCadastroProduto().setVisible(true);
    }//GEN-LAST:event_btnCadProdutosActionPerformed

    private void bnCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnCadClientesActionPerformed
        new TelaCadastroCliente().setVisible(true);
    }//GEN-LAST:event_bnCadClientesActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
       new TelaRelatorios().setVisible(true);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnCadClientes;
    private javax.swing.JButton btnCadProdutos;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
